// Hằng số text UI dùng chung cho toàn bộ trang, tách khỏi component.
export const UI_TEXT = {
  // Metadata website dùng trong thẻ <head>
  META: {
    SITE_NAME: "IELTS Writing AI",
    SITE_DESCRIPTION:
      "Nền tảng luyện IELTS Writing Task 2 tích hợp AI chấm bài",
  },

  // Placeholder và giá trị fallback dùng chung nhiều trang
  COMMON: {
    PLACEHOLDER_EMAIL: "example@email.com",
    PLACEHOLDER_PASSWORD: "••••••••",
    EMPTY_VALUE: "—",
    FALLBACK_USER_NAME: "bạn",
    FALLBACK_USER_DISPLAY: "Người dùng",
  },

  // Thông báo validation cho form
  VALIDATION: {
    EMAIL_INVALID: "Email không hợp lệ",
    PASSWORD_MIN: "Mật khẩu tối thiểu 6 ký tự",
    FULL_NAME_MIN: "Tên tối thiểu 2 ký tự",
    FULL_NAME_MAX: "Tên tối đa 30 ký tự",
    PASSWORD_MISMATCH: "Mật khẩu xác nhận không khớp",
  },

  // Text trang đăng nhập
  LOGIN: {
    HEADING: "IELTS Writing AI",
    SUBHEADING: "Đăng nhập để tiếp tục luyện tập",
    LABEL_EMAIL: "Email",
    LABEL_PASSWORD: "Mật khẩu",
    BTN_SUBMIT: "Đăng nhập",
    LINK_REGISTER: "Đăng ký ngay",
    HINT_NO_ACCOUNT: "Chưa có tài khoản?",
    TOAST_ERROR: "Email hoặc mật khẩu không đúng",
    TOAST_SUCCESS: "Đăng nhập thành công!",
  },

  // Text trang đăng ký
  REGISTER: {
    HEADING: "Tạo tài khoản",
    SUBHEADING: "Bắt đầu hành trình IELTS của bạn",
    LABEL_FULL_NAME: "Họ và tên",
    LABEL_EMAIL: "Email",
    LABEL_PASSWORD: "Mật khẩu",
    LABEL_CONFIRM_PASSWORD: "Xác nhận mật khẩu",
    PLACEHOLDER_FULL_NAME: "Nguyễn Văn A",
    BTN_SUBMIT: "Đăng ký",
    LINK_LOGIN: "Đăng nhập",
    HINT_HAS_ACCOUNT: "Đã có tài khoản?",
    TOAST_SUCCESS_REDIRECT: "Đăng ký thành công! Vui lòng đăng nhập.",
    TOAST_SUCCESS_AUTO_LOGIN: "Chào mừng bạn đến với IELTS Writing AI!",
    TOAST_ERROR_FALLBACK: "Đăng ký thất bại",
  },

  // Phiên bản & changelog
  VERSION: {
    PAGE_TITLE: "Lịch sử cập nhật",
    CURRENT_VERSION_LABEL: "Phiên bản hiện tại",
    SIDEBAR_LABEL: "Lịch sử cập nhật",
  },

  // Nhãn điều hướng sidebar
  SIDEBAR: {
    LOGO_TEXT: "IELTS Writing AI",
    NAV_DASHBOARD: "Tổng quan",
    NAV_PRACTICE: "Luyện tập",
    NAV_COURSES: "Khóa học",
    NAV_SAMPLE_ESSAYS: "Bài mẫu",
    NAV_FLASHCARDS: "Thẻ từ vựng",
    NAV_NOTEBOOK: "Sổ tay",
  },

  // Text topbar
  TOPBAR: {
    GREETING: "Chào mừng trở lại",
    BTN_LOGOUT: "Đăng xuất",
  },

  // Text trang dashboard (có hàm nội suy giá trị động)
  DASHBOARD: {
    GREETING: (name: string) => `Xin chào, ${name}`,
    SUBHEADING: "Hôm nay bạn muốn luyện tập chủ đề nào?",
    STAT_SUBMISSIONS: "Bài đã nộp",
    STAT_AVG_BAND: "Band trung bình",
    STAT_STREAK: "Streak hiện tại",
    STAT_FLASHCARD_SETS: "Bộ flashcard",
    QUICK_PRACTICE_TITLE: "Luyện viết ngay",
    QUICK_PRACTICE_DESC: "Chọn đề và bắt đầu viết",
    QUICK_FLASHCARD_TITLE: "Ôn luyện flashcard",
    QUICK_FLASHCARD_DESC: (n: number) => `${n} bộ thẻ đang chờ bạn`,
    QUICK_FLASHCARD_EMPTY: "Tạo bộ thẻ đầu tiên của bạn",
    RECENT_TITLE: "Bài nộp gần đây",
    RECENT_EMPTY: "Hãy bắt đầu hành trình!",
    RECENT_EMPTY_HINT: "Nộp bài đầu tiên để nhận phân tích chi tiết từ AI",
    RECENT_SUBMISSION_LABEL: (n: number) => `Bài luyện #${n}`,
    ERROR_CHART_TITLE: "Phân tích lỗi thường gặp",
    ERROR_CHART_EMPTY: "Sẵn sàng luyện tập chưa?",
    ERROR_CHART_EMPTY_HINT: "Nộp bài để AI phân tích điểm yếu và giúp bạn cải thiện",
    ERROR_CHART_SUFFIX: "lần",
    CHART_EMPTY: "Chưa có dữ liệu",
    CHART_TITLE: "Band Score",
  },

  // Text trang luyện viết
  PRACTICE: {
    BTN_SAVE_DRAFT: "Lưu nháp",
    BTN_SUBMIT: "Nộp bài",
    BTN_SUBMITTING: "Đang nộp...",
    LABEL_WORD_COUNT: (count: number) => `${count} từ`,
    WORD_COUNT_MIN: 250, // số từ tối thiểu khuyến nghị cho Task 2
    WORD_COUNT_HINT: "Tối thiểu 250 từ",
    DRAFT_SAVED: "Đã lưu nháp",
    TOPIC_LABEL: "Chủ đề",
    TARGET_BAND_LABEL: "Mục tiêu",
    TASK_INSTRUCTION: "Hướng dẫn làm bài",
    GRADING_IDLE: "Viết bài và nhấn Nộp bài để AI chấm điểm",
    GRADING_WAITING: "Đang chờ hàng đợi...",
    GRADING_PROCESSING: "AI đang chấm bài...",
    GRADING_COMPLETED: "Chấm bài hoàn tất!",
    GRADING_FAILED: "Có lỗi xảy ra khi chấm bài",
    GRADING_LABEL_OVERALL: "Band dự kiến",
    PLACEHOLDER_ESSAY: "Bắt đầu viết bài của bạn tại đây...",
  },

  // Text trang kết quả chấm bài
  RESULT: {
    TOOLTIP_SUGGESTION_LABEL: "Gợi ý",
    SEVERITY_HIGH: "Cao",
    SEVERITY_MEDIUM: "Trung bình",
    SEVERITY_LOW: "Thấp",
    SCORE_LABEL_TASK: "Task Response",
    SCORE_LABEL_COHERENCE: "Coherence & Cohesion",
    SCORE_LABEL_LEXICAL: "Lexical Resource",
    SCORE_LABEL_GRAMMAR: "Grammatical Range",
    SCORE_LABEL_OVERALL: "Overall Band",
    FEEDBACK_GENERAL: "Nhận xét chung",
    FEEDBACK_STRENGTHS: "Điểm mạnh",
    FEEDBACK_IMPROVEMENTS: "Cần cải thiện",
    ERROR_LIST_TITLE: "Danh sách lỗi",
    ERROR_FILTER_ALL: "Tất cả",
    RESULT_LOADING: "Đang tải kết quả...",
    RESULT_NOT_FOUND: "Không tìm thấy kết quả",
    TOOLTIP_CATEGORY_LABEL: "Loại lỗi",
    TOOLTIP_SEVERITY_LABEL: "Mức độ",
  },

  // Text trang bài mẫu
  SAMPLE_ESSAYS: {
    PAGE_TITLE: "Bài mẫu IELTS",
    PAGE_SUBTITLE: "Tham khảo các bài viết mẫu đã được AI chấm điểm",
    BADGE_TASK_1: "Task 1",
    BADGE_TASK_2: "Task 2",
    CARD_READ_MORE: "Đọc bài",
    FILTER_TASK_ALL: "Tất cả",
    FILTER_TASK_1: "Task 1",
    FILTER_TASK_2: "Task 2",
    FILTER_TOPIC_ALL: "Tất cả chủ đề",
    FILTER_BAND_ALL: "Mọi band",
    FILTER_BAND_LOW: "Band 5.0",
    FILTER_BAND_MID: "Band 6.0",
    FILTER_BAND_HIGH: "Band 7+",
    BTN_RESET_FILTER: "Đặt lại",
    EMPTY_STATE: "Không có bài mẫu nào phù hợp",
    EMPTY_STATE_HINT: "Thử thay đổi bộ lọc",
    DETAIL_BACK: "Danh sách bài mẫu",
    DETAIL_LABEL_QUESTION: "Đề bài",
    DETAIL_LABEL_INFO: "Thông tin bài viết",
    DETAIL_LABEL_BAND: "Band Score",
    DETAIL_LABEL_TASK: "Loại bài",
    DETAIL_LABEL_TOPIC: "Chủ đề",
    DETAIL_LABEL_AUTHOR: "Tác giả",
    TOOLTIP_TYPE_LABEL: "Điểm hay",
    DETAIL_LABEL_OUTLINE: "Dàn ý",
    DETAIL_NO_ANNOTATION: "Bài viết này chưa có phân tích lỗi chi tiết",
    DETAIL_NOT_FOUND: "Không tìm thấy bài mẫu",
  },

  // Text trang notebook
  NOTEBOOK: {
    PAGE_TITLE:          "Sổ tay của tôi",
    PAGE_SUBTITLE:       "Ghi chú cá nhân trong quá trình luyện tập",
    BTN_NEW_NOTE:        "Ghi chú mới",
    BTN_SAVE:            "Lưu thay đổi",
    BTN_CREATE:          "Tạo ghi chú",
    UNTITLED:            "Ghi chú không có tiêu đề",
    NOTE_COUNT_LABEL:    "ghi chú",
    PLACEHOLDER_TITLE:   "Tiêu đề (tùy chọn)",
    PLACEHOLDER_CONTENT: "Viết ghi chú của bạn...",
    EMPTY_LIST:          "Chưa có ghi chú nào",
    EMPTY_LIST_HINT:     "Nhấn \"Ghi chú mới\" để bắt đầu",
    EMPTY_SELECT:        "Chọn một ghi chú hoặc tạo mới",
    EMPTY_SELECT_HINT:   "Ghi chú của bạn sẽ hiển thị ở đây",
    DELETE_CONFIRM:      "Bạn có chắc muốn xóa ghi chú này không?",
    FILTER_ALL:          "Tất cả ghi chú",
    FILTER_UNCATEGORIZED:"Chưa phân loại",
    COLLECTIONS_LABEL:   "Bộ sưu tập",
    BTN_NEW_COLLECTION:  "Tạo bộ sưu tập mới",
    COLLECTION_NONE:     "Không có",
    COLLECTION_FIELD:    "Bộ",
    COLLECTION_RENAME:   "Đổi tên",
    COLLECTION_DELETE:   "Xoá bộ",
    DELETE_COLLECTION_CONFIRM: "Xoá bộ sưu tập? Các ghi chú trong bộ sẽ chuyển về Chưa phân loại.",
    MODAL_TITLE_CREATE:  "Ghi chú mới",
    MODAL_TITLE_EDIT:    "Chỉnh sửa ghi chú",
    MENU_EDIT:           "Chỉnh sửa",
    MENU_DELETE:         "Xoá",
  },

  // Text trang courses (có hàm format thời lượng)
  COURSES: {
    PAGE_TITLE: "Khoá học",
    PAGE_SUBTITLE: "Tài liệu học IELTS Writing theo từng band điểm",
    FILTER_TOPIC_ALL: "Tất cả chủ đề",
    FILTER_BAND_ALL: "Tất cả band",
    FILTER_BAND_5_0: "Band 5.0",
    FILTER_BAND_6_0: "Band 6.0",
    FILTER_BAND_7_PLUS: "Band 7+",
    EMPTY_COURSES: "Không có khoá học nào",
    EMPTY_COURSES_HINT: "Thử thay đổi bộ lọc chủ đề",
    EMPTY_LESSONS: "Khoá học chưa có bài học",
    LABEL_LESSONS: (n: number) => `${n} bài học`,
    LABEL_INSTRUCTOR: "Giảng viên",
    TAB_VIDEOS: "Video",
    TAB_VOCABULARY: "Từ vựng",
    TAB_GRAMMAR: "Ngữ pháp",
    TAB_NOTES: "Ghi chú",
    EMPTY_VIDEOS: "Chưa có video",
    EMPTY_VOCABULARY: "Chưa có từ vựng",
    EMPTY_GRAMMAR: "Chưa có ngữ pháp",
    EMPTY_NOTES: "Chưa có ghi chú",
    // Format thời lượng giây sang chuỗi MM:SS.
    LABEL_DURATION: (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`,
    BTN_RESET_FILTER: "Đặt lại",
    DETAIL_BACK: "Quay lại",
    DETAIL_SELECT_LESSON: "Chọn một bài học để bắt đầu",
    DETAIL_LESSON_LOADING: "Đang tải bài học...",
  },

  // Text trang flashcards
  FLASHCARDS: {
    PAGE_TITLE: "Thẻ ghi nhớ",
    PAGE_SUBTITLE: "Ôn tập với hệ thống lặp lại thông minh",
    BTN_NEW_SET: "Tạo bộ thẻ",
    BTN_START_REVIEW: "Ôn tập",
    BTN_ADD_CARD: "Thêm thẻ",
    BTN_SAVE: "Lưu",
    BTN_CANCEL: "Huỷ",
    BTN_FLIP: "Lật thẻ",
    LABEL_DUE: (n: number) => `${n} thẻ cần ôn`,
    PLACEHOLDER_SET_TITLE: "Tên bộ thẻ...",
    PLACEHOLDER_SET_DESC: "Mô tả (tuỳ chọn)...",
    PLACEHOLDER_FRONT: "Mặt trước (từ vựng / câu hỏi)...",
    PLACEHOLDER_BACK: "Mặt sau (nghĩa / đáp án)...",
    EMPTY_SETS: "Chưa có bộ thẻ nào",
    EMPTY_SETS_HINT: "Nhấn \"Tạo bộ thẻ\" để bắt đầu",
    EMPTY_CARDS: "Bộ thẻ chưa có thẻ nào",
    EMPTY_CARDS_HINT: "Nhấn \"Thêm thẻ\" để thêm thẻ đầu tiên",
    EMPTY_REVIEW: "Không có thẻ nào cần ôn hôm nay",
    EMPTY_REVIEW_HINT: "Quay lại vào ngày mai nhé!",
    REVIEW_PROGRESS: (cur: number, total: number) => `${cur} / ${total}`,
    REVIEW_COMPLETE: "Hoàn thành buổi ôn tập!",
    REVIEW_COMPLETE_HINT: (n: number) => `Bạn đã ôn ${n} thẻ trong buổi này`,
    REVIEW_QUALITY_PROMPT: "Bạn nhớ được đến mức nào?",
    REVIEW_FLIP_HINT: "Nhấn vào thẻ để xem đáp án",
    CARD_FACE_FRONT: "Mặt trước",
    CARD_FACE_BACK: "Mặt sau",
    // Nhãn theo nhóm ReviewQuality: 0–1 quên, 2–3 còn mơ hồ, 4–5 nhớ rõ.
    QUALITY_LABELS: ["Không nhớ", "Còn lơ mơ", "Nhớ rõ"] as const,
    TAB_FLASHCARDS: "Flashcard",
    TAB_NOTES: "Ghi chú",
    EMPTY_LESSON_FLASHCARDS: "Bài học này chưa có flashcard",
    EMPTY_LESSON_NOTES: "Bài học này chưa có ghi chú",
    BTN_REVIEW_LESSON_SET: "Ôn tập bộ thẻ này",
    SECTION_LESSON_SETS: "Bộ thẻ bài học",
    SECTION_PERSONAL_SETS: "Bộ thẻ của tôi",
    EMPTY_PERSONAL_SETS: "Bạn chưa có bộ thẻ nào",
    EMPTY_PERSONAL_SETS_HINT: "Nhấn \"Tạo bộ thẻ\" để bắt đầu",
    CONFIRM_DELETE_SET: "Bộ thẻ và toàn bộ thẻ bên trong sẽ bị xoá.",
    DETAIL_BACK: "Quay lại",
    LABEL_CARD_COUNT: (n: number) => `${n} thẻ`,
    FORM_TITLE_ADD: "Thêm thẻ mới",
    FORM_TITLE_EDIT: "Chỉnh sửa thẻ",
    NOT_FOUND: "Không tìm thấy bộ thẻ",
    CONFIRM_DELETE_CARD: "Bạn có chắc muốn xoá thẻ này không?",
    BTN_REVIEW_SET: "Ôn tập bộ này",
    BTN_BACK_TO_LIST: "Danh sách thẻ",
    REVIEW_MODE_TITLE: "Chọn chế độ ôn tập",
    REVIEW_MODE_ALL: "Học tất cả",
    REVIEW_MODE_DUE: "Thẻ đến hạn",
    REVIEW_MODE_DUE_EMPTY: "Không có thẻ nào đến hạn",
  },

  // Text trang danh sách đề luyện tập
  PRACTICE_LIST: {
    HEADING: "Luyện tập",
    SUBHEADING: "Chọn đề và bắt đầu luyện viết",
    BTN_RANDOM: "Đề ngẫu nhiên",
    BTN_START: "Bắt đầu",
    FILTER_ALL_TOPICS: "Tất cả chủ đề",
    FILTER_DIFFICULTY: "Độ khó",
    FILTER_ALL_DIFFICULTY: "Tất cả",
    LABEL_ATTEMPTS: (n: number) => `${n} lượt làm`,
    EMPTY_TITLE: "Không có đề thi nào",
    EMPTY_DESC: "Thử thay đổi bộ lọc hoặc quay lại sau.",
    // Index 0 bỏ trống; 1 = Dễ, 2 = Trung bình, 3 = Khó.
    DIFFICULTY_LABELS: ["", "Dễ", "Trung bình", "Khó"] as const,
  },




  // ── Admin Dashboard ────────────────────────────────────────────────────────
  ADMIN: {
    // Dùng chung cho mọi trang admin
    COMMON: {
      LOADING:          "Đang tải...",
      SAVING:           "Đang lưu...",
      DELETING:         "Đang xóa...",
      BTN_ADD:          "Thêm mới",
      BTN_SAVE:         "Lưu thay đổi",
      BTN_CREATE:       "Tạo mới",
      BTN_CANCEL:       "Hủy",
      BTN_UPDATE:       "Cập nhật",
      BTN_DELETE:       "Xóa",
      BTN_EDIT:         "Chỉnh sửa",
      DIALOG_DELETE_TITLE: "Xóa bài học",
      DIALOG_DELETE_MSG:   "Bạn có chắc muốn xóa bài học này?",
      STATUS_LOCKED:    "Bị khóa",
      FILTER_ALL_TOPICS: "Tất cả chủ đề",
      STATUS_PUBLISHED: "Xuất bản",
      STATUS_DRAFT:     "Nháp",
      STATUS_ACTIVE:    "Hoạt động",
      STATUS_HIDDEN:    "Ẩn",
      COL_TITLE:        "Tiêu đề",
      COL_TOPIC:        "Chủ đề",
      COL_STATUS:       "Trạng thái",
      COL_ACTIONS:      "Thao tác",
      SELECT_TOPIC:     "Chọn chủ đề",
    },

    // Topics
    TOPICS: {
      PAGE_TITLE:        "Chủ đề",
      UNIT:              "chủ đề",
      BTN_ADD:           "Thêm chủ đề",
      EMPTY_TITLE:       "Chưa có chủ đề nào",
      EMPTY_HINT:        'Nhấn "Thêm chủ đề" để bắt đầu',
      NO_DESC:           "Chưa có mô tả",
      DELETE_TITLE:      "Xóa chủ đề",
      DELETE_MSG:        "Bạn có chắc muốn xóa chủ đề này? Hành động này không thể hoàn tác.",
      MODAL_CREATE_TITLE: "Thêm chủ đề mới",
      MODAL_EDIT_TITLE:   "Chỉnh sửa chủ đề",
      MODAL_CREATE_HINT:  "Điền thông tin để tạo chủ đề",
      LABEL_NAME:         "Tên chủ đề",
      LABEL_DESC:         "Mô tả",
      LABEL_STATUS:       "Trạng thái",
      PLACEHOLDER_NAME:   "VD: Technology and Society",
      PLACEHOLDER_DESC:   "Mô tả ngắn về chủ đề này...",
      STATUS_ACTIVE:      "Hoạt động",
      STATUS_HIDDEN:      "Ẩn",
      STATUS_HIDDEN_HINT: "Ẩn sẽ không hiện với học viên",
      BTN_CREATE:         "Tạo chủ đề",
      REQUIRED_NAME:      "Vui lòng nhập tên chủ đề",
    },

    // Courses
    COURSES: {
      PAGE_TITLE:          "Khóa học",
      UNIT:                "khóa học",
      BTN_ADD:             "Thêm khóa học",
      EMPTY_TITLE:         "Chưa có khóa học nào",
      EMPTY_HINT:          'Nhấn "Thêm khóa học" để bắt đầu',
      EMPTY_FILTER:        "Không có khóa học nào thuộc chủ đề này",
      COL_LESSONS:         "Bài học",
      DELETE_TITLE:        "Xóa khóa học",
      DELETE_MSG:          "Bạn có chắc muốn xóa khóa học này?",
      FORM_LABEL_TITLE:    "Tên khóa học",
      FORM_LABEL_TOPIC:    "Chủ đề",
      FORM_LABEL_STATUS:   "Trạng thái",
      FORM_LABEL_DESC:     "Mô tả",
      FORM_PH_TITLE:       "VD: IELTS Writing Task 2: Technology and Society",
      FORM_PH_DESC:        "Mô tả ngắn về khóa học...",
      FORM_REQ_TITLE:      "Vui lòng nhập tên khóa học",
      FORM_REQ_TOPIC:      "Vui lòng chọn chủ đề",
      STATUS_PUBLISHED:    "Đã xuất bản",
      STATUS_DRAFT:        "Nháp",
      BTN_CREATE:          "Tạo khóa học",
    },

    // Lessons
    LESSONS: {
      PAGE_TITLE_PREFIX:   "Bài học",
      UNIT:                "bài học",
      BTN_ADD:             "Thêm bài học",
      EMPTY:               "Chưa có bài học nào",
      COUNT_VIDEO:         "video",
      COUNT_VOCAB:         "từ vựng",
      COUNT_GRAMMAR:       "ngữ pháp",
      DELETE_TITLE:        "Xóa bài học",
      DELETE_MSG:          "Bạn có chắc muốn xóa bài học này?",
      // Form modal
      MODAL_CREATE_TITLE:  "Thêm bài học mới",
      MODAL_EDIT_TITLE:    "Chỉnh sửa bài học",
      FORM_LABEL_TITLE:    "Tên bài học",
      FORM_LABEL_BAND:     "Target Band",
      FORM_LABEL_DESC:     "Mô tả",
      FORM_LABEL_NOTES:    "Nội dung ghi chú (Markdown)",
      FORM_LABEL_STATUS:   "Trạng thái",
      FORM_PH_TITLE:       "VD: Task Response: Cách phân tích đề",
      FORM_PH_DESC:        "Mô tả bài học...",
      FORM_PH_NOTES:       "## Heading\n\nNội dung bài học...",
      FORM_REQ_TITLE:      "Vui lòng nhập tên",
      STATUS_PUBLISHED:    "Xuất bản",
      STATUS_DRAFT:        "Nháp",
      BTN_CREATE:          "Tạo mới",
    },

    // Exam Questions
    EXAM_QUESTIONS: {
      PAGE_TITLE:    "Đề thi",
      UNIT:          "đề thi",
      BTN_ADD:       "Thêm đề thi",
      EMPTY:         "Chưa có đề thi nào",
      EMPTY_FILTER:  "Không có đề thi nào cho chủ đề này",
      COL_DIFFICULTY: "Độ khó",
      COL_ATTEMPTS:   "Lượt làm",
      DELETE_TITLE:   "Xóa đề thi",
      DELETE_MSG:     "Bạn có chắc muốn xóa đề thi này?",
      DIFF_EASY:      "Dễ",
      DIFF_MEDIUM:    "Trung bình",
      DIFF_HARD:      "Khó",
      // Form
      FORM_LABEL_TITLE:        "Tiêu đề đề thi",
      FORM_LABEL_PROMPT:       "Nội dung đề thi",
      FORM_LABEL_OUTLINE:      "Gợi ý outline",
      FORM_LABEL_TOPIC:        "Chủ đề",
      FORM_LABEL_DIFFICULTY:   "Độ khó",
      FORM_LABEL_STATUS:       "Trạng thái",
      FORM_LABEL_SOURCE:       "Nguồn tham khảo",
      FORM_PH_TITLE:           "VD: Task 2: Environment and Climate Change",
      FORM_PH_PROMPT:          "You should spend about 40 minutes on this task. Write about the following topic...",
      FORM_PH_OUTLINE:         "Introduction: ...\nBody 1: ...\nBody 2: ...\nConclusion: ...",
      FORM_PH_SOURCE:          "Cambridge IELTS 15, Test 1",
      FORM_OPT_NO_TOPIC:       "Không có",
      FORM_REQ_TITLE:          "Vui lòng nhập tiêu đề",
      FORM_REQ_PROMPT:         "Vui lòng nhập nội dung đề",
      BTN_CREATE:              "Tạo đề thi",
      STATUS_PUBLISHED:        "Xuất bản",
      STATUS_DRAFT:            "Nháp",
    },

    // Sample Essays
    SAMPLE_ESSAYS: {
      PAGE_TITLE:   "Bài mẫu",
      UNIT:         "bài mẫu",
      BTN_ADD:      "Thêm bài mẫu",
      EMPTY:        "Chưa có bài mẫu nào",
      EMPTY_FILTER: "Không có bài mẫu nào cho chủ đề này",
      COL_BAND:     "Band",
      DELETE_TITLE: "Xóa bài mẫu",
      DELETE_MSG:   "Bạn có chắc muốn xóa bài mẫu này?",
      // Form modal
      MODAL_CREATE_TITLE:   "Thêm bài mẫu mới",
      MODAL_EDIT_TITLE:     "Chỉnh sửa bài mẫu",
      FORM_LABEL_TITLE:     "Tiêu đề",
      FORM_LABEL_TOPIC:     "Chủ đề",
      FORM_LABEL_PROMPT:    "Nội dung đề thi",
      FORM_LABEL_OUTLINE:   "Outline",
      FORM_LABEL_CONTENT:   "Nội dung bài mẫu",
      FORM_LABEL_AUTHOR:    "Tác giả",
      FORM_LABEL_BAND:      "Band score",
      FORM_LABEL_STATUS:    "Trạng thái",
      FORM_PH_TITLE:        "VD: Band 7.5 Essay: Environmental Pollution",
      FORM_PH_PROMPT:       "You should spend about 40 minutes on this task...",
      FORM_PH_OUTLINE:      "Introduction: ...\nBody: ...\nConclusion: ...",
      FORM_PH_CONTENT:      "Nội dung bài essay...",
      FORM_PH_AUTHOR:       "Tên tác giả",
      FORM_REQ_TITLE:       "Vui lòng nhập tiêu đề",
      FORM_REQ_TOPIC:       "Vui lòng chọn chủ đề",
      FORM_REQ_PROMPT:      "Vui lòng nhập đề",
      FORM_REQ_OUTLINE:     "Vui lòng nhập outline",
      FORM_REQ_CONTENT:     "Vui lòng nhập bài mẫu",
      FORM_REQ_BAND:        "Vui lòng nhập band score",
      FORM_VAL_BAND:        "Band score từ 0 đến 9",
      STATUS_PUBLISHED:     "Xuất bản",
      STATUS_DRAFT:         "Nháp",
      BTN_CREATE:           "Tạo mới",
    },

    // Dashboard (admin/page.tsx)
    DASHBOARD: {
      PAGE_TITLE:           "Admin Dashboard",
      PAGE_SUBTITLE:        "Thống kê tổng quan hệ thống",
      STAT_TOTAL_USERS:     "Tổng người dùng",
      STAT_TOTAL_SUBS:      "Tổng bài nộp",
      STAT_COMPLETED:       "Bài đã chấm xong",
      STAT_AVG_BAND:        "Band score TB",
      STAT_TOPICS:          "Chủ đề",
      STAT_COURSES:         "Khóa học",
      STAT_EXAM_QUESTIONS:  "Đề thi",
      STAT_SAMPLE_ESSAYS:   "Bài mẫu",
      QUICK_TOPICS_LABEL:   "Quản lý Chủ đề",
      QUICK_TOPICS_DESC:    "Thêm, sửa, xóa topics",
      QUICK_COURSES_LABEL:  "Quản lý Khóa học",
      QUICK_COURSES_DESC:   "CRUD courses và lessons",
      QUICK_EXAM_LABEL:     "Quản lý Đề thi",
      QUICK_EXAM_DESC:      "Thêm đề IELTS Writing Task 2",
      QUICK_ESSAYS_LABEL:   "Quản lý Bài mẫu",
      QUICK_ESSAYS_DESC:    "Thêm bài mẫu có band score",
      QUICK_USERS_LABEL:    "Quản lý Người dùng",
      QUICK_USERS_DESC:     "Xem danh sách và phân quyền",
    },

    // Page navigation headers
    PAGE_HEADERS: {
      BTN_BACK_LIST:          "Quay lại danh sách",
      COURSE_NEW_TITLE:       "Thêm khóa học mới",
      COURSE_EDIT_INFO:       "Thông tin khóa học",
      COURSE_LESSONS_SECTION: "Bài học",
      COURSE_LESSONS_EMPTY:   'Chưa có bài học nào, nhấn "Thêm bài học" để bắt đầu',
      EXAM_NEW_TITLE:         "Thêm đề thi mới",
      EXAM_NEW_SUBTITLE:      "Điền thông tin để tạo đề thi IELTS Writing Task 2",
      EXAM_EDIT_TITLE:        "Chỉnh sửa đề thi",
      EXAM_NOT_FOUND:         "Không tìm thấy đề thi",
      ESSAY_NEW_TITLE:        "Thêm bài mẫu mới",
      ESSAY_NEW_SUBTITLE:     "Tạo bài mẫu IELTS Writing Task 2 với highlight annotations",
      ESSAY_EDIT_SUBTITLE:    "Chỉnh sửa nội dung và highlight annotations",
    },

    // Users
    USERS: {
      PAGE_TITLE:       "Người dùng",
      UNIT:             "người dùng",
      COL_USER:         "Người dùng",
      COL_EMAIL:        "Email",
      COL_ROLE:         "Role",
      COL_CREATED_AT:   "Ngày tạo",
      STATUS_ACTIVE:    "Hoạt động",
      STATUS_LOCKED:    "Bị khóa",
      PAGINATION_LABEL: (page: number, total: number) => `Trang ${page} / ${total}`,
      BTN_PREV:         "Trước",
      BTN_NEXT:         "Sau",
      MODAL_TITLE:      "Chỉnh sửa user",
      MODAL_EMAIL_HINT: "Email không thể thay đổi",
      MODAL_LABEL_NAME: "Họ tên",
      MODAL_LABEL_ROLE: "Role",
      MODAL_LABEL_STATUS:   "Trạng thái",
      // User detail page
      DETAIL_BACK:          "Quay lại Người dùng",
      DETAIL_DATE_CREATED:  "Ngày tạo:",
      DETAIL_LAST_LOGIN:    "Đăng nhập:",
      DETAIL_STATUS_ACTIVE: "Đang hoạt động",
      SUBS_SECTION_TITLE:   "Lịch sử bài nộp",
      SUBS_EMPTY:           "Người dùng chưa nộp bài nào",
      SUBS_LOAD_ERROR:      "Không tải được lịch sử bài nộp",
      SUBS_RETRY_HINT:      "Vui lòng thử tải lại trang.",
      SUBS_COL_EXAM:        "Đề thi",
      SUBS_COL_ATTEMPT:     "Lần thứ",
      SUBS_COL_BAND:        "Band Score",
      SUBS_COL_WORDS:       "Số từ",
      SUBS_COL_DATE:        "Ngày nộp",
      SUBS_COL_DETAIL:      "Chi tiết",
      SUBS_BTN_VIEW:        "Xem chi tiết",
      SUBS_STATUS_DRAFT:       "Nháp",
      SUBS_STATUS_SUBMITTED:   "Đã nộp",
      SUBS_STATUS_PROCESSING:  "Đang chấm",
      SUBS_STATUS_COMPLETED:   "Hoàn thành",
      SUBS_STATUS_FAILED:      "Lỗi",
    },

    // Sample Essay Form (full-page with annotations)
    ESSAY_FORM: {
      FORM_LABEL_TITLE:    "Tiêu đề",
      FORM_LABEL_PROMPT:   "Nội dung đề thi",
      FORM_LABEL_OUTLINE:  "Dàn ý",
      FORM_LABEL_CONTENT:  "Nội dung bài mẫu",
      FORM_LABEL_TOPIC:    "Chủ đề",
      FORM_LABEL_AUTHOR:   "Tác giả",
      FORM_LABEL_BAND:     "Band Score",
      FORM_LABEL_STATUS:   "Trạng thái",
      FORM_PH_TITLE:       "VD: Band 7.5 Essay: Environmental Pollution",
      FORM_PH_PROMPT:      "You should spend about 40 minutes on this task...",
      FORM_PH_OUTLINE:     "Introduction: ...\nBody 1: ...\nBody 2: ...\nConclusion: ...",
      FORM_PH_CONTENT:     "Nội dung bài essay hoàn chỉnh...",
      FORM_PH_AUTHOR:      "Tên tác giả",
      FORM_REQ_TITLE:      "Vui lòng nhập tiêu đề",
      FORM_REQ_PROMPT:     "Vui lòng nhập nội dung đề",
      FORM_REQ_OUTLINE:    "Vui lòng nhập dàn ý",
      FORM_REQ_CONTENT:    "Vui lòng nhập nội dung bài viết",
      FORM_REQ_TOPIC:      "Vui lòng chọn chủ đề",
      FORM_REQ_BAND:       "Vui lòng nhập band score",
      FORM_VAL_BAND:       "Band score từ 0 đến 9",
      STATUS_PUBLISHED:    "Xuất bản",
      STATUS_DRAFT:        "Nháp",
      BTN_CREATE:          "Tạo bài mẫu",
      PREVIEW_EXPAND:      "Mở rộng",
      PREVIEW_COLLAPSE:    "Thu gọn",
      PREVIEW_EMPTY:       "Chưa có nội dung bài viết.",
      ANN_SECTION_TITLE:   "Highlights",
      ANN_BTN_ADD:         "Thêm",
      ANN_EMPTY:           "Chưa có highlight nào",
      ANN_LABEL_TEXT:      "Đoạn text cần highlight",
      ANN_LABEL_TYPE:      "Loại",
      ANN_LABEL_EXPL:      "Giải thích",
      ANN_PH_TEXT:         "Dán đoạn text từ bài essay...",
      ANN_PH_EXPL:         "Tại sao đoạn này hay? Phân tích từ vựng/ngữ pháp...",
    },

    // Lesson Media Manager (Video / Vocabulary / Grammar / Flashcard panels)
    MEDIA: {
      TAB_VIDEOS:     "Videos",
      TAB_VOCAB:      "Từ vựng",
      TAB_GRAMMAR:    "Ngữ pháp",
      TAB_FLASHCARD:  "Flashcard",
      // Video panel
      VIDEO_EDIT_HDR:     "Chỉnh sửa video",
      VIDEO_LABEL_TITLE:  "Tiêu đề video",
      VIDEO_LABEL_URL:    "URL video",
      VIDEO_LABEL_DUR:    "Thời lượng (giây)",
      VIDEO_PH_TITLE:     "VD: IELTS Task Response Tips",
      VIDEO_PH_URL:       "https://www.youtube.com/watch?v=...",
      VIDEO_PH_DUR:       "VD: 720 (= 12 phút)",
      VIDEO_BTN_ADD:      "Thêm video",
      VIDEO_TITLE_HIDE:   "Ẩn preview",
      VIDEO_TITLE_SHOW:   "Xem video",
      // Vocabulary panel
      VOCAB_EDIT_HDR:     "Chỉnh sửa từ vựng",
      VOCAB_LABEL_WORD:   "Từ vựng",
      VOCAB_LABEL_IPA:    "Phiên âm IPA",
      VOCAB_LABEL_DEF:    "Định nghĩa (EN)",
      VOCAB_LABEL_TRANS:  "Nghĩa tiếng Việt",
      VOCAB_LABEL_EX:     "Ví dụ",
      VOCAB_LABEL_TS:     "Mốc thời gian (giây)",
      VOCAB_LABEL_CTX:    "Câu ngữ cảnh trong video",
      VOCAB_PH_WORD:      "VD: electrification",
      VOCAB_PH_IPA:       "/ɪˌlektrɪfɪˈkeɪʃn/",
      VOCAB_PH_DEF:       "The process of transitioning to electric power",
      VOCAB_PH_TRANS:     "điện khí hóa",
      VOCAB_PH_EX:        "The electrification of transport could reduce urban emissions.",
      VOCAB_PH_TS:        "VD: 96.5",
      VOCAB_PH_CTX:       "Câu chứa từ trong video",
      VOCAB_BTN_ADD:      "Thêm từ vựng",
      // Grammar panel
      GRAMMAR_EDIT_HDR:    "Chỉnh sửa ngữ pháp",
      GRAMMAR_LABEL_TITLE: "Tiêu đề",
      GRAMMAR_LABEL_STRUCT:"Cấu trúc",
      GRAMMAR_LABEL_EXPL:  "Giải thích",
      GRAMMAR_LABEL_EX:    "Ví dụ",
      GRAMMAR_LABEL_TS:    "Mốc thời gian (giây)",
      GRAMMAR_LABEL_CTX:   "Câu ngữ cảnh trong video",
      GRAMMAR_PH_TITLE:    "VD: Passive Voice with Modal Verbs",
      GRAMMAR_PH_STRUCT:   "S + modal + be + past participle",
      GRAMMAR_PH_EXPL:     "Dùng để diễn đạt khả năng/bắt buộc ở dạng bị động...",
      GRAMMAR_PH_EX:       "Many jobs could be replaced by artificial intelligence.",
      GRAMMAR_PH_TS:       "VD: 152.4",
      GRAMMAR_PH_CTX:      "Câu chứa cấu trúc trong video",
      GRAMMAR_BTN_ADD:     "Thêm ngữ pháp",
      // Flashcard panel
      FC_EMPTY:            "Lesson này chưa có flashcard set",
      FC_BTN_CREATE_SET:   "Tạo Flashcard Set",
      FC_EDIT_HDR:         "Chỉnh sửa thẻ",
      FC_LABEL_FRONT:      "Mặt trước",
      FC_LABEL_BACK:       "Mặt sau",
      FC_BTN_ADD:          "Thêm thẻ",
      FC_CARD_COUNT_UNIT:  "thẻ",
    },
  },

} as const;
